name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0

    - name: Install Packages
      run: pnpm install --frozen-lockfile     

    - name: Build Client
      working-directory: ./client
      run: pnpm build

    - name: Build Server
      working-directory: ./server
      run: pnpm build   
